### ISSUE TITLE
Missing Plugin Exception Can't Run The WifiEvents 

### ISSUE THREAD

**Issue by pr-1** [mintware-de/flutter_p2p#16]
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method unregister on channel de.mintware.flutter_p2p/flutter_p2p)
E/flutter (26927): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154)
E/flutter (26927): <asynchronous suspension>
E/flutter (26927): #1      FlutterP2p.unregister (package:flutter_p2p/plugin.dart:40)
E/flutter (26927): <asynchronous suspension>
E/flutter (26927): 
Syncing files to device SM M305F...
E/flutter (28646): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method isLocationPermissionGranted on channel de.mintware.flutter_p2p/flutter_p2p)
E/flutter (28646): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (28646): <asynchronous suspension>
E/flutter (28646): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (28646): #2      FlutterP2p.isLocationPermissionGranted (package:flutter_p2p/plugin.dart:24:27)
E/flutter (28646): #3      _MyAppState._checkPermission (package:flutter_p2p_example/main.dart:149:27)
E/flutter (28646): #4      _MyAppState._register (package:flutter_p2p_example/main.dart:61:16)
E/flutter (28646): #5      _MyAppState.initState (package:flutter_p2p_example/main.dart:41:5)
E/flutter (28646): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
E/flutter (28646): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (28646): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (28646): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (28646): #10     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1148:16)
E/flutter (28646): #11     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1119:5)
E/flutter (28646): #12     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1061:17)
E/flutter (28646): #13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
E/flutter (28646): #14     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1060:13)
E/flutter (28646): #15     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:941:7)
E/flutter (28646): #16     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:922:7)
E/flutter (28646): #17     _rootRun (dart:async/zone.dart:1180:38)
E/flutter (28646): #18     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (28646): #19     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (28646): #20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (28646): #21     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (28646): #22     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (28646): #23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter (28646): #24     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (28646): #25     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (28646): #26     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (28646): #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (28646): 
D/InputMethodManager(28646): prepareNavigationBarInfo() DecorView@62325b3[MainActivity]
D/InputMethodManager(28646): getNavigationBarColor() -855310
V/InputMethodManager(28646): Starting input: tba=de.mintware.flutter_p2p_example ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(28646): startInputInner - Id : 0
I/InputMethodManager(28646): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(28646): Input channel destroyed: 'ClientS', fd=86
D/ViewRootImpl@af29ca5[MainActivity](28646): stopped(true) old=false
D/SurfaceView(28646): windowStopped(true) false io.flutter.view.FlutterView{e155e21 VFE...... ........ 0,0-1080,2340} of ViewRootImpl@af29ca5[MainActivity]
D/SurfaceView(28646): surfaceDestroyed callback.size 1 #1 io.flutter.view.FlutterView{e155e21 VFE...... ........ 0,0-1080,2340}
W/libEGL  (28646): EGLNativeWindowType 0x7739781010 disconnect failed
D/SurfaceView(28646): remove() io.flutter.view.FlutterView{e155e21 VFE...... ........ 0,0-1080,2340} Surface(name=SurfaceView - de.mintware.flutter_p2p_example/de.mintware.flutter_p2p_example.MainActivity@e155e21@0)/@0x22e641e
E/flutter (28646): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method unregister on channel de.mintware.flutter_p2p/flutter_p2p)
E/flutter (28646): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (28646): <asynchronous suspension>
E/flutter (28646): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (28646): #2      FlutterP2p.unregister (package:flutter_p2p/plugin.dart:40:27)
E/flutter (28646): #3      _MyAppState._unregister (package:flutter_p2p_example/main.dart:102:16)
E/flutter (28646): #4      _MyAppState.didChangeAppLifecycleState (package:flutter_p2p_example/main.dart:56:7)
E/flutter (28646): #5      WidgetsBinding.handleAppLifecycleStateChanged (package:flutter/src/widgets/binding.dart:655:16)
E/flutter (28646): #6      SchedulerBinding._handleLifecycleMessage (package:flutter/src/scheduler/binding.dart:349:5)
E/flutter (28646): #7      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:74:49)
E/flutter (28646): #8      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:199:33)
E/flutter (28646): #9      _invoke3.<anonymous closure> (dart:ui/hooks.dart:290:15)
E/flutter (28646): #10     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (28646): #11     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (28646): #12     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (28646): #13     _invoke3 (dart:ui/hooks.dart:289:10)
E/flutter (28646): #14     _dispatchPlatformMessage (dart:ui/hooks.dart:164:5)
E/flutter (28646): 
D/ViewRootImpl@af29ca5[MainActivity](28646): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(28646): prepareNavigationBarInfo() DecorView@62325b3[MainActivity]
D/InputMethodManager(28646): getNavigationBarColor() -855310
E/ViewRootImpl@af29ca5[MainActivity](28646): Surface is not valid.
E/ViewRootImpl@af29ca5[MainActivity](28646): Surface is not valid.
W/IInputConnectionWrapper(28646): getExtractedText on inactive InputConnection
E/ViewRootImpl@af29ca5[MainActivity](28646): Surface is not valid.
D/SurfaceView(28646): onWindowVisibilityChanged(8) false io.flutter.view.FlutterView{e155e21 VFE...... ........ 0,0-1080,2340} of ViewRootImpl@af29ca5[MainActivity]
W/libEGL  (28646): EGLNativeWindowType 0x779821d850 disconnect failed
D/ViewRootImpl@af29ca5[MainActivity](28646): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)8 dur=21 res=0x5 s={false 0} ch=false
D/InputTransport(28646): Input channel destroyed: 'ClientS', fd=87
D/SurfaceView(28646): onWindowVisibilityChanged(4) false io.flutter.view.FlutterView{e155e21 VFE...... ........ 0,0-1080,2340} of ViewRootImpl@af29ca5[MainActivity]
D/ViewRootImpl@af29ca5[MainActivity](28646): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)4 dur=14 res=0x1 s={false 0} ch=false
D/ViewRootImpl@af29ca5[MainActivity](28646): stopped(false) old=true
D/SurfaceView(28646): windowStopped(false) false io.flutter.view.FlutterView{e155e21 VFE...... ........ 0,0-1080,2340} of ViewRootImpl@af29ca5[MainActivity]
D/SurfaceView(28646): onWindowVisibilityChanged(0) true io.flutter.view.FlutterView{e155e21 VFE...... ........ 0,0-1080,2340} of ViewRootImpl@af29ca5[MainActivity]
D/ViewRootImpl@af29ca5[MainActivity](28646): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)0 dur=23 res=0x7 s={true 512065208320} ch=true
D/OpenGLRenderer(28646): createReliableSurface : 0x779821d840, 0x7739770000
D/mali_winsys(28646): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/SurfaceView(28646): surfaceCreated 1 #8 io.flutter.view.FlutterView{e155e21 VFE...... ........ 0,0-1080,2340}
D/mali_winsys(28646): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/SurfaceView(28646): surfaceChanged (1080,2340) 1 #8 io.flutter.view.FlutterView{e155e21 VFE...... ........ 0,0-1080,2340}
D/ViewRootImpl@af29ca5[MainActivity](28646): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(28646): prepareNavigationBarInfo() DecorView@62325b3[MainActivity]
D/InputMethodManager(28646): getNavigationBarColor() -855310
D/InputMethodManager(28646): prepareNavigationBarInfo() DecorView@62325b3[MainActivity]
D/InputMethodManager(28646): getNavigationBarColor() -855310
V/InputMethodManager(28646): Starting input: tba=de.mintware.flutter_p2p_example ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(28646): startInputInner - Id : 0
I/InputMethodManager(28646): startInputInner - mService.startInputOrWindowGainedFocus
D/ViewRootImpl@af29ca5[MainActivity](28646): stopped(false) old=false
E/flutter (28646): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method isLocationPermissionGranted on channel de.mintware.flutter_p2p/flutter_p2p)
E/flutter (28646): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (28646): <asynchronous suspension>
E/flutter (28646): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (28646): #2      FlutterP2p.isLocationPermissionGranted (package:flutter_p2p/plugin.dart:24:27)
E/flutter (28646): #3      _MyAppState._checkPermission (package:flutter_p2p_example/main.dart:149:27)
E/flutter (28646): #4      _MyAppState._register (package:flutter_p2p_example/main.dart:61:16)
E/flutter (28646): #5      _MyAppState.didChangeAppLifecycleState (package:flutter_p2p_example/main.dart:54:7)
E/flutter (28646): #6      WidgetsBinding.handleAppLifecycleStateChanged (package:flutter/src/widgets/binding.dart:655:16)
E/flutter (28646): #7      SchedulerBinding._handleLifecycleMessage (package:flutter/src/scheduler/binding.dart:349:5)
E/flutter (28646): #8      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:74:49)
E/flutter (28646): #9      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:199:33)
E/flutter (28646): #10     _invoke3.<anonymous closure> (dart:ui/hooks.dart:290:15)
E/flutter (28646): #11     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (28646): #12     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (28646): #13     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (28646): #14     _invoke3 (dart:ui/hooks.dart:289:10)
E/flutter (28646): #15     _dispatchPlatformMessage (dart:ui/hooks.dart:164:5)
E/flutter (28646): 
D/ViewRootImpl@af29ca5[MainActivity](28646): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(28646): prepareNavigationBarInfo() DecorView@62325b3[MainActivity]
D/InputMethodManager(28646): getNavigationBarColor() -855310
D/InputTransport(28646): Input channel destroyed: 'ClientS', fd=89
D/SurfaceView(28646): onWindowVisibilityChanged(8) false io.flutter.view.FlutterView{e155e21 VFE...... ........ 0,0-1080,2340} of ViewRootImpl@af29ca5[MainActivity]
D/SurfaceView(28646): surfaceDestroyed callback.size 1 #2 io.flutter.view.FlutterView{e155e21 VFE...... ........ 0,0-1080,2340}
W/libEGL  (28646): EGLNativeWindowType 0x7739856010 disconnect failed
D/SurfaceView(28646): remove() io.flutter.view.FlutterView{e155e21 VFE...... ........ 0,0-1080,2340} Surface(name=SurfaceView - de.mintware.flutter_p2p_example/de.mintware.flutter_p2p_example.MainActivity@e155e21@1)/@0xd75f4ff
W/libEGL  (28646): EGLNativeWindowType 0x779821d850 disconnect failed
D/ViewRootImpl@af29ca5[MainActivity](28646): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)8 dur=31 res=0x5 s={false 0} ch=true
D/ViewRootImpl@af29ca5[MainActivity](28646): stopped(true) old=false
D/SurfaceView(28646): windowStopped(true) false io.flutter.view.FlutterView{e155e21 VFE...... ........ 0,0-1080,2340} of ViewRootImpl@af29ca5[MainActivity]
E/flutter (28646): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method unregister on channel de.mintware.flutter_p2p/flutter_p2p)
E/flutter (28646): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (28646): <asynchronous suspension>
E/flutter (28646): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (28646): #2      FlutterP2p.unregister (package:flutter_p2p/plugin.dart:40:27)
E/flutter (28646): #3      _MyAppState._unregister (package:flutter_p2p_example/main.dart:102:16)
E/flutter (28646): #4      _MyAppState.didChangeAppLifecycleState (package:flutter_p2p_example/main.dart:56:7)
E/flutter (28646): #5      WidgetsBinding.handleAppLifecycleStateChanged (package:flutter/src/widgets/binding.dart:655:16)
E/flutter (28646): #6      SchedulerBinding._handleLifecycleMessage (package:flutter/src/scheduler/binding.dart:349:5)
E/flutter (28646): #7      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:74:49)
E/flutter (28646): #8      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:199:33)
E/flutter (28646): #9      _invoke3.<anonymous closure> (dart:ui/hooks.dart:290:15)
E/flutter (28646): #10     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (28646): #11     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (28646): #12     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (28646): #13     _invoke3 (dart:ui/hooks.dart:289:10)
E/flutter (28646): #14     _dispatchPlatformMessage (dart:ui/hooks.dart:164:5)
E/flutter (28646): 
I/flutter (31535): stateChange: true

**Comment by pr-1** [comment]
Cloned the example project.
The App is getting built fine but when I run it this exception throws up.

Tried flutter clean and rerun but it's not working.

**Comment by pr-1** [comment]
I downgraded the kotlin version as there were dependency errors and build was initially failing.
