### ISSUE TITLE
project ':flutter_p2p' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

### ISSUE THREAD

**Issue by storm-monkey** [mintware-de/flutter_p2p#23]
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_p2p' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

I have upgraded flutter to the latest version.Plz help me.

flutter doctor -v
![image](https://user-images.githubusercontent.com/63580709/94358247-42889b80-00bd-11eb-9ef5-258a4457aabd.png)

**Comment by AdvaitKale01** [comment]
Same! Any Solutions?

**Comment by storm-monkey** [comment]
> Same! Any Solutions?

In   "**your_project/android/build.gradle**" file , under dependencies change **classpath 'com.android.tools.build:gradle:3.5.0**' to  **classpath 'com.android.tools.build:gradle:3.2.1'**
This builds the project successfully.But,I don't think this is the right solution.
Developers has to fix this issue!!..

![image](https://user-images.githubusercontent.com/63580709/94768137-22622080-03cc-11eb-8470-ef21c423aa8a.png)

**Comment by AdvaitKale01** [comment]
> > Same! Any Solutions?
> 
> In "**your_project/android/build.gradle**" file , under dependencies change **classpath 'com.android.tools.build:gradle:3.5.0**' to **classpath 'com.android.tools.build:gradle:3.2.1'**
> This builds the project successfully.But,I don't think this is the right solution.
> Developers has to fix this issue!!..
> 
> ![image](https://user-images.githubusercontent.com/63580709/94768137-22622080-03cc-11eb-8470-ef21c423aa8a.png)

The apo runs in debug but not in apk release mode. Should use nearby connections api by google

**Comment by eldadbarkai** [comment]
I am new in Flutter/Dart.

However, I wrote a tiny application that tries to work with flutter_p2p.

I have the same problem that is described above. 

I have changed com.android.tools.build:gradle:3.5.0 to com.android.tools.build:gradle:3.2.1.

When I run the application and call to isLocationPermissionGranted, I receive the following error:

E/flutter ( 3443): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method isLocationPermissionGranted on channel de.mintware.flutter_p2p/flutter_p2p)
E/flutter ( 3443): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 3443): <asynchronous suspension>
E/flutter ( 3443): #1      FlutterP2p.isLocationPermissionGranted (package:flutter_p2p/plugin.dart:24:12)
E/flutter ( 3443): <asynchronous suspension>


What can I do in order to solve this issue.

**Comment by muhammedkamal** [comment]
> > > Same! Any Solutions?
> > 
> > 
> > In "**your_project/android/build.gradle**" file , under dependencies change **classpath 'com.android.tools.build:gradle:3.5.0**' to **classpath 'com.android.tools.build:gradle:3.2.1'**
> > This builds the project successfully.But,I don't think this is the right solution.
> > Developers has to fix this issue!!..
> > ![image](https://user-images.githubusercontent.com/63580709/94768137-22622080-03cc-11eb-8470-ef21c423aa8a.png)
> 
> The apo runs in debug but not in apk release mode. Should use nearby connections api by google

after I do this I recieved a new error 
* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > 'org.gradle.api.file.RegularFileProperty org.gradle.api.file.ProjectLayout.fileProperty(org.gradle.api.provider.Provider)'
